name: Terraform Plan, Apply or Destroy

on:
  workflow_dispatch:
    inputs:
      actions:
        description: 'choose terraform action (plan, apply or destroy)'
        required: true
        default: 'plan'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.2  # change to your Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: ${{ github.event.inputs.actions == 'plan'}}
        run: terraform plan


      - name: Terraform Apply
        if: ${{ github.event.inputs.actions == 'apply'}}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.actions == 'destroy'}}
        run: terraform destroy -auto-approve -input=false